# Test Controller configuration
testController:
  replicas: 1
  image:
    repository: nautilus444/test-controller
    tag: latest
    pullPolicy: Always

# Chrome Node configuration
chromeNode:
  replicas: 1
  image:
    repository: nautilus444/chrome-node
    tag: latest
    pullPolicy: IfNotPresent
