# Test Controller configuration
testController:
  replicas: 1
  image:
    repository: nautilus444/test-controller
    tag: latest
    pullPolicy: Always

# Chrome Node configuration
chromeNode:
  replicas: 1
  image:
    repository: selenium/standalone-chrome
    tag: latest
    pullPolicy: IfNotPresent
