# Test Controller configuration
testController:
  replicas: 1
  image:
    repository: nautilus444/test-controller
    tag: latest
    pullPolicy: Always
    resources:
      requests:
        memory: "200Mi"
        cpu: "100m"
      limits:
        memory: "400Mi"
        cpu: "300m"
  role: arn:aws:iam::242201276816:role/selenium_eks_role
# Chrome Node configuration
chromeNode:
  replicas: 1
  image:
    repository: selenium/standalone-chrome
    tag: latest
    pullPolicy: IfNotPresent
    resources:
      requests:
        memory: "450Mi"
        cpu: "150m"
      limits:
        memory: "500Mi"
        cpu: "300m"