# Test Controller configuration
testController:
  replicas: 1
  image:
    repository: nautilus444/test-controller
    tag: latest
    pullPolicy: IfNotPresent

# Chrome Node configuration
chromeNode:
  replicas: 1
  image:
    repository: nautilus444/selenium-chrome-node
    tag: latest
    pullPolicy: IfNotPresent
