# templates/chrome-node-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-chrome-node
spec:
  replicas: {{ .Values.chromeNode.replicas }}
  selector:
    matchLabels:
      app: chrome-node
  template:
    metadata:
      labels:
        app: chrome-node
    spec:
      containers:
        - name: chrome-node
          image: "{{ .Values.chromeNode.image.repository }}:{{ .Values.chromeNode.image.tag }}"
          ports:
            - containerPort: 4444
          imagePullPolicy: {{ .Values.chromeNode.image.pullPolicy }}
          env:
          - name: JAVA_OPTS
            value: "-Dotel.traces.exporter=none"
          readinessProbe:
            httpGet:
              path: /status
              port: 4444
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 40