apiVersion: apps/v1
kind: Deployment
metadata:
  name: chrome-node-deployment
spec:
  replicas: "{{ .Values.chromeNode.replicas }}"
  selector:
    matchLabels:
      app: chrome-node
  template:
    metadata:
      labels:
        app: chrome-node
    spec:
      containers:
        - name: chrome-node
          image: selenium/standalone-chrome:latest
          ports:
            - containerPort: 4444