apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-controller-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-controller
  template:
    metadata:
      labels:
        app: test-controller
    spec:
      containers:
        - name: test-controller
          image: "{{ .Values.testController.image }}"
          env:
            - name: REMOTE_SELENIUM_URL
              value: "http://chrome-node-service:4444/wd/hub"
          ports:
            - containerPort: 8000