# templates/test-controller-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-test-controller
spec:
  serviceAccountName: s3-access-sa
  replicas: {{ .Values.testController.replicas }}
  selector:
    matchLabels:
      app: test-controller
  template:
    metadata:
      labels:
        app: test-controller
    spec:
      containers:
        - name: test-controller
          image: "{{ .Values.testController.image.repository }}:{{ .Values.testController.image.tag }}"
          ports:
            - containerPort: 8080
          imagePullPolicy: {{ .Values.testController.image.pullPolicy }}
